# Generated by Django 4.1.3 on 2022-11-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfamilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nac',
            field=models.DateTimeField(null=True),
        ),
    ]
